### ISSUE TITLE
new release tag?

### ISSUE THREAD

**Issue by ilovezfs** [Dushistov/sdcv#10]
It would be great if we could get a new stable release tag here on GitHub for the Homebrew formula. The current formula is building with

```
"http://svn.code.sf.net/p/sdcv/code/trunk", :revision => "76"
version "0.5-2013-09-10"
```

I'm updating that to what I believe is equivalent here on GitHub

```
  url "https://github.com/Dushistov/sdcv.git",
      :revision => "c347ae7da9b7969e00696b18035d9a7d200e43e3"
  version "0.5-2013-09-10"
  revision 1
```

But it would be much preferred if we could build from a GitHub source archive tarball (automatically generated when you create any tag) or an actual release tarball you post manually. Ideally, the new tag would include your new work, assuming it's ready to be designated stable, but even just a tag of the svn revision 76 equivalent would be preferred to the current situation.

Thanks!

**Comment by ilovezfs** [comment]
@Dushistov ping on this.

**Comment by baimafeima** [comment]
@Dushistov Is this project still maintained? Without any versioned tarballs here on GitHub it cannot suggest it for inclusion to the repositories of my operating system of choice.

**Comment by Dushistov** [comment]
@baimafeima @ilovezfs  I created new tag and github created new release:

https://github.com/Dushistov/sdcv/releases

I am not sure that `sdcv` has enough changes to make new release, but because of it have no
releases since migration to github from sf.net, I think I can made one.

**Comment by ilovezfs** [comment]
@Dushistov Thank you: https://github.com/Homebrew/homebrew-core/pull/12784

**Comment by baimafeima** [comment]
@Dushistov Thanks a lot.
