### ISSUE TITLE
Thoughts on removing glib as a dependency?

### ISSUE THREAD

**Issue by houqp** [Dushistov/sdcv#12]
Just curious how feasible it is to remove glib as a dependency since compiling glib for android devices is not fun :(

**Comment by Dushistov** [comment]
Actually, I think about removing C/C++ as dependency. So glib also go away.

**Comment by houqp** [comment]
You meant rewriting it in pure C?

**Comment by houqp** [comment]
Oh shit, I just saw the rust branch, nice!

**Comment by houqp** [comment]
I have been thinking of rewriting it in C or rust. Now that you already started working on it, I will just wait :P  
Can't wait to in corporate the new version into KOReader! Also, let me know if there is anything I can help :)
