### ISSUE TITLE
How to compile this program on Windows?

### ISSUE THREAD

**Issue by zhixing2017** [Dushistov/sdcv#18]
Hello, Thanks for your job.

Now I want to use this program on Windows7. Is there a compiled `.exe` that can be used on Windows?
Or Which tool should I use to compile this program?

I am not familiar with `cmake`. I used `msys2` and `cmake` to compile the program. Error occured.
Can you give some details, please? 

Best regards.

**Comment by Frenzie** [comment]
> Error occured. Can you give some details, please?

I think you've got that at least partially backwards. Shouldn't you share the error log so people can take a look at it? ;-)
