### ISSUE TITLE
Change location of $HOME/.stardict

### ISSUE THREAD

**Issue by andyperisho** [Dushistov/sdcv#41]
Is it possible to change the location of `$HOME/.stardict` to something else like, for example $HOME/.local/.stardict` ?

I tried setting the `STARDICT_DATA_DIR`, but that did not change the fact that `sdcv` created the `.stardict` dir (empty) on every run.

**Comment by Dushistov** [comment]
> Is it possible to change the location of $HOME/.stardict to something else like, for example $HOME/.local/.stardict` ?
> I tried setting the STARDICT_DATA_DIR, but that did not change the fact that sdcv created the .stardict dir (empty) on every run.

You can look at `man sdcv`. There are two type of directories where `sdcv` search dictionaries,
system's directotires (like `/usr/share/stardict/dic`) and user's directories (`~/.stardict/dic`).
All options (`STARDICT_DATA_DIR` and `--data-dir=`) are used for changing path to system's directories, not path to user's dictionaries.

If you do not use system's dictories, you can run `sdcv` like this:
```sh
sdcv -x --data-dir=$HOME/.local/stardict
```

**Comment by Dushistov** [comment]
Or use symlinks

**Comment by andyperisho** [comment]
I did try the command you shared, and it still created an empty `~/.stardict` folder! All i'm looking for is to not have such a dir created!

**Comment by Dushistov** [comment]
>I did try the command you shared, and it still created an empty ~/.stardict folder! All i'm >looking for is to not have such a dir created!

`$HOME/.stardict` creation is not optional, but you can always set `HOME` variable to what you want:
```sh
HOME=$HOME/.local sdcv
```
after that you find that `$HOME/.local/.stardict` exists, but no `$HOME/.stardict`

**Comment by andyperisho** [comment]
Thx, this solved the problem for me!
