### ISSUE TITLE
sdcv_ordering example

### ISSUE THREAD

**Issue by 1094** [Dushistov/sdcv#42]
I have been look for examples for quite some time now and can not find one. Does anyone have an example I could use so I know what this files needs to look like and include?  
Thanks.

**Comment by Dushistov** [comment]
@1094 

For example you run

```
$ sdcv -l
Dictionary's name   Word count
oxford    43808
Merriam-Webster's Collegiate    119769
```

you take the first column of output, in other words `Dictionary's name`,
and put it to `~/.sdcv_ordering` line by line:
```
$ cat ~/.sdcv_ordering 
Merriam-Webster's Collegiate
oxford
$ 
```

that's all, at the next run of sdcv, for example `sdcv man` you get at first
translation from `Merriam-Webster's Collegiate` and after that from `oxford` dictionary
and after that all other translations.

**Comment by 1094** [comment]
I honestly thought it was going to be something much more complicated than that.
Thank you!
