### ISSUE TITLE
use .syn files 

### ISSUE THREAD

**Issue by Dushistov** [Dushistov/sdcv#8]
SDCV does not use the synonyms information that is in dictionaries that come with a .syn file. In some languages synonyms are very important as a word can have many variations depending on gender, tense, etc.

**Comment by ecraven** [comment]
Is there a reason this is not implemented, or has just no-one had the time to do it?

**Comment by Dushistov** [comment]
> or has just no-one had the time to do it?

I am afraid that this is true, no-one want spend time for this feature.
